### ISSUE TITLE
pw_sequential - update proofing

### ISSUE THREAD

**Issue by cfoellmann** [convissor/login-security-solution#38]
this is a nice feature but 100% non-extendable the WP way.

If a user (site admin) adds a custom file it will be lost on update! Yes, it could be contributed here but it should not be required.

Possible solutions:
- move file contents (`pw_sequential/*`) to a function. Function returns sequences that can be extended by an action hook
- extend the function `is_pw_sequential_file` to look for sequence files in a directory outside of `wp-content/plugins/` like the `load_plugin_textdomain()` function does

**Comment by kevindoole** [comment]
You could actually use `wp_insert_post` with an unregistered post type. Definitely feels a bit hacky, but from what I've seen this is a legit way to store info like this without causing side effects for users.

The LSS interface could then offer a very basic crud for these dictionary and sequence posts through wp-admin.
