### ISSUE TITLE
Enhancement Request - HTTP HEADER IP

### ISSUE THREAD

**Issue by skywaymsn** [convissor/login-security-solution#52]
An option to use the IP in an HTTP header such as X-Forwarded-For or REQUEST.  This allows the plugin to remain useful even behind a load balancer or proxy using SNAT.  As built, this plugin simply block all attempts as they appear to originate from the same IP.

Otherwise, awesome plugin.

**Comment by convissor** [comment]
> An option to use the IP in an HTTP header such as X-Forwarded-For or REQUEST.  This allows the plugin to remain useful even behind a load balancer or proxy using SNAT.  As built, this plugin simply block all attempts as they appear to originate from the same IP.

See the installation instructions:
https://wordpress.org/plugins/login-security-solution/installation/

**Comment by skywaymsn** [comment]
*headdesk*  That's what I get for using the built-in GUI installer and not paying attention.  Thank you.
